version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PSW}
      MYSQL_DATABASE: ${SQL_DB_ADDRESS_RENTABLE}, ${SQL_DB_ADDRESS_USER}, ${SQL_DB_ADDRESS_CONTRACT}
    networks:
      exam-package:

  api-gateway:
    container_name: api-gateway
    build:
      context: /api-gateway
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    networks:
      exam-package:
    restart: on-failure
networks:
  exam-package: